<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Bellatrix.BugReporting\Bellatrix.BugReporting.csproj" />
      <ProjectReference Include="..\..\..\Bellatrix.Web\Bellatrix.Web.csproj" />
    </ItemGroup>

</Project>
