<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\shared\SharedAssemblyInfo.targets" />

	<ItemGroup>
		<PackageReference Include="Appium.WebDriver" Version="8.0.1" />
		<!--<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />-->
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.1" />
        <PackageReference Include="MSTest" Version="4.0.2" />
        <PackageReference Include="NUnit" Version="4.4.0" />
		<!--<PackageReference Include="System.Drawing.Primitives" Version="4.3.0" />-->
	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bellatrix.Core\Bellatrix.Core.csproj" />
    <ProjectReference Include="..\Bellatrix.Layout\Bellatrix.Layout.csproj" />
    <ProjectReference Include="..\Bellatrix.Plugins.Screenshots\Bellatrix.Plugins.Screenshots.csproj" />
    <ProjectReference Include="..\Bellatrix.Plugins.Video\Bellatrix.Plugins.Video.csproj" />
  </ItemGroup>
</Project>