name: Tests on Windows

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 8.0.x
      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 9.0.x
      - name: Clean
        run: dotnet clean
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Debug --no-restore --no-parallel
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal --filter Category=CI
